### ISSUE TITLE
Runtime bug: PyO3 modules may only be initialized once per interpreter process

### ISSUE THREAD

**Issue by npapapietro** [omnilib/vscode-ufmt#83]
Encountering a vscode error when saving.

Context, I'm in a monorepo managed by nx.

When I save on fresh opening vscode, it works without error. Second save will throw the error below

```
formatting complete
formatting in-process
CWD Linter: /home/user/git/repo
formatting with:  ufmt==2.1.0  black==23.7.0  libcst==1.0.1  usort==1.0.7
[Error - 11:46:16 AM] uncaught exception:
Traceback (most recent call last):
  File "/home/user/.vscode-server/extensions/omnilib.ufmt-2023.4.3-linux-x64/bundled/tool/server.py", line 341, in _run_tool_on_document
    ufmt_result = ufmt.ufmt_bytes(
  File "/home/user/envs/py38-env/lib/python3.8/site-packages/ufmt/core.py", line 84, in ufmt_bytes
    raise result.error
  File "/home/user/envs/py38-env/lib/python3.8/site-packages/usort/api.py", line 31, in usort
    module = try_parse(data=data, path=path)
  File "/home/user/envs/py38-env/lib/python3.8/site-packages/usort/util.py", line 65, in try_parse
    mod = cst.parse_module(
  File "/home/user/envs/py38-env/lib/python3.8/site-packages/libcst/_parser/entrypoints.py", line 109, in parse_module
    result = _parse(
  File "/home/user/envs/py38-env/lib/python3.8/site-packages/libcst/_parser/entrypoints.py", line 42, in _parse
    from libcst.native import parse_expression, parse_module, parse_statement
ImportError: PyO3 modules may only be initialized once per interpreter process
```

**Comment by amyreese** [comment]
By default, the plugin will attempt to import packages from the environment.  Can you try setting the ufmt "import strategy" preference to `useBundled` and see if that prevents the import error?  The plugin still comes with `libcst==0.4.9`, so maybe there's an issue with the newer release?

**Comment by npapapietro** [comment]
Thanks! I think that did the trick.

**Comment by amyreese** [comment]
Just published a new release that defaults to "useBundled" and also disables the attempt to reload extensions, which together should resolve this problem.
